### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

### ISSUE THREAD

**Issue by henokyemam** [inspera/blackbricks#5] opened 2020-11-24 04:20 UTC
blackbricks --remote /Users/heyema@microsoft.com/Alcanna/Generate_Sale_Payment_Line
Traceback (most recent call last):
  File "/Users/henokyemam/opt/anaconda3/envs/experiment/bin/blackbricks", line 8, in <module>
    sys.exit(app())
  File "/Users/henokyemam/opt/anaconda3/envs/experiment/lib/python3.6/site-packages/typer/main.py", line 214, in __call__
    return get_command(self)(*args, **kwargs)
  File "/Users/henokyemam/opt/anaconda3/envs/experiment/lib/python3.6/site-packages/typer/main.py", line 239, in get_command
    click_command = get_command_from_info(typer_instance.registered_commands[0])
  File "/Users/henokyemam/opt/anaconda3/envs/experiment/lib/python3.6/site-packages/typer/main.py", line 442, in get_command_from_info
    deprecated=command_info.deprecated,
TypeError: __init__() got an unexpected keyword argument 'no_args_is_help'

**Comment by bsamseth** [comment] 2020-11-24 07:59
Thank you for reporting this. I can't seem to reproduce this on a fresh install. The keyword argument this error message complains about is not used anywhere in the code. This leaves me to think that the issue is somehow related to some incompatible package versions in your environment. 

Please provide the output of these commands, from within your conda environment:
```
python --version
pip --version
blackbricks --version
pip freeze
```

**Comment by akbo** [comment] 2020-11-25 18:07
I just had the same problem. The reason was that my Anaconda installation had a very old version of [click](https://pypi.org/project/click/) installed (v7.0 from 2018). 

The no_args_is_help keyword argument was introduced in v7.1 (see [the click changelog](https://click.palletsprojects.com/en/7.x/changelog/) -> it is mentioned there).

So the fix is to update click, e.g. `conda update -n experiment click` or make sure you pin click to at least v7.1 in your conda environment file.

**Comment by bsamseth** [comment] 2020-11-27 08:43
That makes sense. Still, I'm a bit surprised this wasn't resolved when blackbricks was installed. The setup file requires `typer >= 0.3.0`, which again requires `click >= 7.1.1, <7.2.0`. Perhaps anaconda doesn't automatically upgrade packages you already have on the system. Regardless, I don't see what I can change on "my side" to ensure this doesn't happen. At best I can put something in the FAQ.

I will close this for now, but feel free to reopen if there is something you think should be changed in blackbricks.

**Closed as completed by bsamseth** 2020-11-27 08:43 UTC
