### ISSUE TITLE
Only include .py files

### ISSUE THREAD

**Issue by cm-halfspace** [inspera/blackbricks#46] opened 2023-08-11 11:51 UTC
Hi,

It seems that `blackbricks` right now runs on every file (I get the following error, see below). 

```
InvalidInput: Cannot parse: 1:0: !/dbfs/databricks/init_scripts/install_prod_artifacts.sh
```

Is it possible in any way to only run `blackbricks` on `.py` files?

**Comment by bsamseth** [comment] 2023-08-11 14:34
If you give it a directory, it will attempt to format any notebook it can find under that directory. It should skip any file that does not have the Databricks notebook header comment as the first line. Without a reproducible example I can't say much about the error you see. If you can provide that, perhaps I can give some better insight. 

You could provide files rather than directories to blackbricks. The shell command `find` is made to do just this type of thing. 

I'll close this for now as I can't help debugging this firther without more information, but I'll reopen if this turns out to be a bug in blackbricks.

**Closed as not planned by bsamseth** 2023-08-11 14:34 UTC
